### ISSUE TITLE
document polkavm

### ISSUE THREAD

**Issue by gogo2464** [koute/polkavm#103]
Hello,

I heard ink! will be deprecated in some years.

Could you document polkavm please? I have no choice other than coding with ink! now.

**Comment by koute** [comment]
What do you mean by "document"?

I think you might be misunderstanding what PolkaVM is. The underlying VM is not something that users using things like Ink! will have to interact with directly; it's just the underlying "engine" that will be used, but the layers above it will mostly take care of interacting with it.

Also, as far as I know Ink! is not being deprecated.

**Comment by gogo2464** [comment]
document the ink! replacement. i think I was on wrong repo
