### ISSUE TITLE
how to use polkavm in wasm runtime?

### ISSUE THREAD

**Issue by xlc** [koute/polkavm#111]
Looks like polkavm crate requires std. I want to run a PolkaVM program in wasm runtime. How can I do it?

**Comment by koute** [comment]
Ideally you'd use it through a host function, but that's still a long ways off, so in the meantime, here:

https://github.com/koute/polkavm/pull/112

This will run interpreter-only, but it should run. Just keep in mind that the interpreter is currently not particularly optimized yet.

**Comment by xlc** [comment]
cool. I got it the runtime compiles.
