### ISSUE TITLE
Make it possible to disable the `sbrk` instruction

### ISSUE THREAD

**Issue by koute** [koute/polkavm#167]
1. Add a `set_allow_sbrk(enabled: bool)` to [`ModuleConfig`](https://docs.rs/polkavm/0.11.0/polkavm/struct.ModuleConfig.html).
2. Have it be `true` by default.
3. When `false` the `sbrk` instruction should act exactly as a trap, both [in the compiler](https://github.com/koute/polkavm/blob/master/crates/polkavm/src/compiler.rs) and [in the interpreter](https://github.com/koute/polkavm/blob/master/crates/polkavm/src/interpreter.rs).
4. The `RawInstance::sbrk` function should be unaffected; we only care about whether the *guest* program can call it or not.
5. Add tests [here](https://github.com/koute/polkavm/blob/master/crates/polkavm/src/tests.rs). See `implicit_trap_after_fallthrough` test for a copy-pastable starting point. Use the builder to make a program which contains `[sbrk(0), ret]` instruction. Enable sync gas metering in `ModuleConfig` and set some initial gas on `RawInstance`. Also remember to do `instance.set_reg(Reg::RA, crate::RETURN_TO_HOST);` so that `ret` can work. (`ret` is just an alias for an indirect jump to the `ra` register, and the `RETURN_TO_HOST` is a special hardcoded address which triggers a "normal" return).

Behavior that should be tested:
- Create module with sbrk disabled, start execution at 0, assert that `run` returns a `Trap`, assert that the amount of gas is 1 less than it started with. (Each instruction currently is hardcoded to use 1 gas.)
- Create module with sbrk enabled, start execution at 0, assert that `run` returns `Finished`, assert that the amount of gas is 2 less than it started with.

**Comment by Nathy-bajo** [comment]
Hi @koute 
Can I take a stab at this?

**Comment by koute** [comment]
@Nathy-bajo Hey, sorry, this issue is already claimed by @aman4150 (:

But if you want to take a stab at something we could probably find you something else to do.

**Comment by Nathy-bajo** [comment]
> @Nathy-bajo Hey, sorry, this issue is already claimed by @aman4150 (:
> 
> But if you want to take a stab at something we could probably find you something else to do.

Alright, what else do you have?
