### ISSUE TITLE
Supply scripts to automatically build a rustc toolchain with support for rv32e/rv64e for all major OSes

### ISSUE THREAD

**Issue by koute** [koute/polkavm#27]
- Add a script which will build a rustc with support for rv32e/rv64e in a Docker and spit out a package that can be installed by rustup.
- This already exists [here](https://github.com/koute/rustc-rv32e), but needs to be extended to be reproducible and containerized so that the resulting binaries work on every system.

**Comment by eagr** [comment]
A couple of questions.

Rather than cloning & patching, could we just clone from a fork? Seems easier this way if we ever need to update the source code, like adding more targets.

Besides `riscv32em_unknown_none_elf`, what other targets would be needed for the purpose of polkavm?

And among those, which builds do you want to offer to people?

**Comment by koute** [comment]
@eagr FYI, in case you wanted to work on this, Gabrielle here is making some headway with getting easily installable packages built:

https://github.com/gabriele-0201/rustc-rv32e-toolchain

So it might make sense to collaborate.

Now, to answer your questions:

> Besides `riscv32em_unknown_none_elf`, what other targets would be needed for the purpose of polkavm?

Currently only this target is necessary, plus a 64-bit one would be nice to have (because we will be adding 64-bit support, and may or may not drop 32-bit support in the future depending on how much difference the 64-bit support makes).

> And among those, which builds do you want to offer to people?

The general idea is to have a one-command installer which will automatically install a standalone `rustup`-compatible toolchain (which can be used as any other toolchain installed through `rustup`) on Linux, macOS and Windows (in this order of priority).

> Rather than cloning & patching, could we just clone from a fork? Seems easier this way if we ever need to update the source code, like adding more targets.

Practically this shouldn't make much difference. I prefer to use a patch simply because then it is obvious what exactly is modified.

We don't want/won't make too many changes to the toolchain anyway, and we will be dropping it once the relevant LLVM patches get finally merged upstream. (This is not supposed to be a long-term fork of the compiler.)

**Comment by eagr** [comment]
> We don't want/won't make too many changes to the toolchain anyway, and we will be dropping it once the relevant LLVM patches get finally merged upstream. (This is not supposed to be a long-term fork of the compiler.)

I see. :)

I was thinking this coud use a few shell scripts and Dockerfiles and provide some prebuilts for major OSes, and that's it. What Gabrielle is building seems to benefit more for your [rustc-rv32e](https://github.com/koute/rustc-rv32e) project, for testing out the scripts on different platforms. Do we really need the GitHub workflow in this repo? @koute

**Comment by koute** [comment]
Mostly closed by https://github.com/paritytech/rustc-rv32e-toolchain/
