### ISSUE TITLE
Polkadoom not working on Mac OS

### ISSUE THREAD

**Issue by filippoweb3** [koute/polkavm#54]
I followed the guidelines in the Readme file, but the terminal is returning the error below

<img width="804" alt="Screenshot 2023-10-17 at 14 50 13" src="https://github.com/koute/polkavm/assets/110459737/ed198749-d888-48d9-a6b6-7ec51487a014">

**Comment by koute** [comment]
Yeah, the `sdl2` crate seems to be broken on too new versions of Xcode.

Should be fixed now!

**Comment by filippoweb3** [comment]
It works now, thanks!
